In [4]:
import numpy as np
import nltk
import pandas as pd
nltk.download('punkt')

import os
import re
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt


from sklearn.model_selection import train_test_split

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/okanciftci/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [5]:
test = pd.read_json("test-data.json","r", encoding="utf8")
train = pd.read_json("train-data.json","r", encoding="utf8")

In [6]:
df = pd.concat([test,train])

In [7]:
df.head()

,_id,corrected_question,intermediary_question,sparql_query,sparql_template_id
0,1701,Which architect of Marine Corps Air Station Ka...,What is the <architect> of the <Marine Corps A...,SELECT DISTINCT ?uri WHERE { <http://dbpedia....,16
1,3293,Which sects people are part of local political...,What is the <faith> of the <political parties>...,SELECT DISTINCT ?uri WHERE { ?x <http://dbpedi...,305
2,2161,List common systems are developed by of the Go...,What is the <developed by> of the <Google Vide...,SELECT DISTINCT ?uri WHERE { <http://dbpedia....,16
3,1136,For which games are Sam Loyd and Eric Schiller...,What is the <known for> of the <Sam Loyd> and ...,SELECT DISTINCT ?uri WHERE { <http://dbpedia.o...,15
4,987,Is Peter Piper Pizza in the pizza industry?,Is <Peter Piper Pizza> the <field of exercise>...,ASK WHERE { <http://dbpedia.org/resource/Peter...,152

In [8]:
def clean_text(text):
    text = text.lower() 
    return text

def cleaner(text):
    text = clean_text(text)
    words = nltk.word_tokenize(text)
    return " ".join(words)

df["question"] = df["corrected_question"].apply(lambda x:  cleaner(x) )
df["query"] = df["sparql_query"].apply(lambda x:  cleaner(x) )

In [9]:
df.head()

,_id,corrected_question,intermediary_question,sparql_query,sparql_template_id,question,query
0,1701,Which architect of Marine Corps Air Station Ka...,What is the <architect> of the <Marine Corps A...,SELECT DISTINCT ?uri WHERE { <http://dbpedia....,16,which architect of marine corps air station ka...,select distinct ? uri where { < http : //dbped...
1,3293,Which sects people are part of local political...,What is the <faith> of the <political parties>...,SELECT DISTINCT ?uri WHERE { ?x <http://dbpedi...,305,which sects people are part of local political...,select distinct ? uri where { ? x < http : //d...
2,2161,List common systems are developed by of the Go...,What is the <developed by> of the <Google Vide...,SELECT DISTINCT ?uri WHERE { <http://dbpedia....,16,list common systems are developed by of the go...,select distinct ? uri where { < http : //dbped...
3,1136,For which games are Sam Loyd and Eric Schiller...,What is the <known for> of the <Sam Loyd> and ...,SELECT DISTINCT ?uri WHERE { <http://dbpedia.o...,15,for which games are sam loyd and eric schiller...,select distinct ? uri where { < http : //dbped...
4,987,Is Peter Piper Pizza in the pizza industry?,Is <Peter Piper Pizza> the <field of exercise>...,ASK WHERE { <http://dbpedia.org/resource/Peter...,152,is peter piper pizza in the pizza industry ?,ask where { < http : //dbpedia.org/resource/pe...

In [11]:
x_train  = df["question"].to_numpy()
y_train_sequences = df["query"].to_numpy()

In [13]:
VOCAB_SIZE = 50000
from tensorflow.keras.preprocessing.text import Tokenizer


def vocab_creater(text_lists, VOCAB_SIZE):
    tokenizer = Tokenizer(num_words=VOCAB_SIZE)
    tokenizer.fit_on_texts(text_lists)
    dictionary = tokenizer.word_index

    word2idx = {}
    idx2word = {}
    for k, v in dictionary.items():
        if v < VOCAB_SIZE:
            word2idx[k] = v
            idx2word[v] = k
        if v >= VOCAB_SIZE-1:
            continue
          
    return word2idx, idx2word

word2idx, idx2word = vocab_creater(text_lists=x_train, VOCAB_SIZE=VOCAB_SIZE)

#Redefine .....
VOCAB_SIZE = len(idx2word) +1

ModuleNotFoundError: No module named 'tensorflow'